---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-15.04
  - name: ubuntu-16.04
  - name: centos-5.11
  - name: centos-6.8
  - name: centos-7.7

suites:
  - name: default
    run_list:
    attributes:
